[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = '0.8.19'

remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src/'
]

[fuzz]
runs = 256

[fmt]
line_length = 120

[rpc_endpoints]
sepolia = "${SEPOLIA_URL}"

[lint]
exclude_lints = ["mixed-case-variable", "unaliased-plain-import"]

fs_permissions = [
    { access = "read-write", path = "./deployed_addresses.txt" },
    { access = "read-write", path = "./" }
]
